Finalization of high level spec: Profiles and forwardings
openBackhaul/MicroWavePerformanceProxy pull request #12
Opened 2024-02-26 08:04 UTC by anacabbar

**Profiles**
	
* File profile removed (no file/database involved in MWPP)
* Integer Profile removed (calculations eventually done outside the Proxy; no configurable variables s.a. number of records to store)

**Profiles List:**
* One string profile per request, to make the query pameters in fields-filter configurable

**Forwardings List:**
* List of forwardings written in compliance with diagrams and service-list

2024-02-27 10:07 UTC, kmohr-soprasteria requested changes
beim 999 Diagramm würde ich auf dem Rückpfeil zu LinkVis die Rückgabe genau angeben. (Den Text der jetzt da steht kann ja ggf. trotzdem stehen bleiben. (Eventuell in einer notes box).
Also zB statt collection of identifiers: externalLabel, originalLtpName (ggf. weitere)
und bei PM-Werten dann AirInterfaceHistoricalPerformances, EthernetContainerHistoricalPerformances usw.

2024-02-27 10:07 UTC, kmohr-soprasteria commented on spec/MicroWavePerformanceProxy+profileInstances.yaml
> +  - profile-name: 'StringProfile'
die profiles von p-004 bis p-006 können weg.
Du brauchst nur für die Forwardings eine profileInstance anzugeben, bei denen auch ein Fields-Filter benutzt wird.

2024-02-27 10:35 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+forwardings.yaml
> +      - client-name: MicroWaveDeviceInventory://core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac?fields=(exte
Reihenfolge für alle Forwardings, ProfileInstances und Diagramme einheitlich gemacht

2024-02-27 10:39 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+forwardings.yaml
>        - server-name: /v1/bequeath-your-data-and-die
Fehlende Service aus dem ApplicationPattern inkludiert

2024-02-27 10:49 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+profileInstances.yaml
> +  - profile-name: 'StringProfile'
Ich glaube, diese "empty strings" erlauben die Fields-Filter konfigurierbar bzw. gegebenfalls anwendbar zu machen (z.B Falls später das Herausfiltern mancher Attribute gewünscht wäre). Siehe ALAP Issue #43 und z.B ALAP-ProfileInstances 002, 003, 006 oder 026.
(Vermutlich wird das Herausfiltern von Performances nicht notwendig, aber von Capabilities könnte sein). Soll ich sie vllt doch lassen, wenn sie nicht stören?

2024-02-27 10:54 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+forwardings.yaml
> -      # [all oam requests]
Kommentar zurück eingetragen

2024-02-27 10:54 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+forwardings.yaml
> -      # [all oam requests]
Kommentar zurück eingetragen

2024-02-27 11:22 UTC, kmohr-soprasteria requested changes

2024-02-27 11:22 UTC, kmohr-soprasteria commented on spec/MicroWavePerformanceProxy+profileInstances.yaml
> +  - profile-name: 'StringProfile'
da bei den Forwardings aktuell keine Fields-Filter benutzt werden, würde ich die hier auch rausnehmen. Sollten die später mal irgendwann benötigt werden, müssten sie dann ergänzt werden.

2024-02-28 08:26 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+profileInstances.yaml
> +  - profile-name: 'StringProfile'
Ich habe das gestern in einem Call mit Thorsten erwähnt, und er empfielt für diese Fälle ProfileInstances mit leeren Strings zu behalten.

2024-02-28 08:28 UTC, merged