Creation oas
openBackhaul/MicroWavePerformanceProxy pull request #15
Opened 2024-03-08 09:42 UTC by anacabbar

2024-03-08 17:18 UTC, PrathibaJee requested changes
Hi Ana , 
The server side stub generated with the provided OAS is working good interms of the request and response schema validation.
Also kindly please find few minor comments. Consider them if they are valid.
Many thanks.

Thanks,
Prathiba J

2024-03-08 17:18 UTC, PrathibaJee commented on spec/MicroWavePerformanceProxy.yaml
> +                              granularity-period:
A description shall be added to point refer the resource in **$RequestForProvidingHistoricalPmDataCausesReadingHistoricalEthernetContainerPerformanceFromCache.EthernetContainerHistoricalPmFromCache**.response.body#ethernet-container-2-0:ethernet-container-historical-performance/historical-performance-data-list/**granularity-period**.

2024-03-08 17:18 UTC, PrathibaJee commented on spec/MicroWavePerformanceProxy.yaml
> +        RequestForProvidingHistoricalPmDataCausesReadingAirInterfaceCapabilitiesFromCache:
In the transmission-mode-list(line no 729) ,  we are formulating the attributes, 
```
transmission-mode-name, 
number-of-states, 
modulation-scheme-name-at-lct, 
channel-bandwidth, code-rate, 
symbol-rate-reduction-factor, 
transmit-power-minimum, 
transmit-power-maximum,
receive-threshold,
transmission-mode-rank,
adaptive-modulation-upshift-level,
adaptive-modulation-downshift-level,
xpic-is-available ,
supported-as-fixed-configuration 
```
from this callback **RequestForProvidingHistoricalPmDataCausesReadingAirInterfaceCapabilitiesFromCache.CapabilitiesFromCache**. 

But , in the response of the callback , we have only the attributes 
```
transmission-mode-name, 
channel-bandwidth, 
modulation-scheme, 
modulation-scheme-name-at-lct.
```
The missing attributes shall also be included in the response

2024-03-08 17:18 UTC, PrathibaJee commented on spec/MicroWavePerformanceProxy.yaml
> +                        ethernet-container-identifiers:
The description of the attributes **ethernet-container-list/interface-name, logical-termination-point-id** shall be updated to point a callback to fomulate the values.

2024-03-08 17:18 UTC, PrathibaJee commented on spec/MicroWavePerformanceProxy.yaml
> +      operationId: provideHistoricalPDataOfDevice
operationId shall be modified to provideHistoricalP**M**DataOfDevice

2024-03-11 11:16 UTC, anacabbar commented on spec/MicroWavePerformanceProxy.yaml
> +                              granularity-period:
Description with ressource reference added

2024-03-11 11:27 UTC, anacabbar commented on spec/MicroWavePerformanceProxy.yaml
> +                        ethernet-container-identifiers:
Callback reference added in description

2024-03-11 13:33 UTC, anacabbar commented on spec/MicroWavePerformanceProxy.yaml
> +        RequestForProvidingHistoricalPmDataCausesReadingAirInterfaceCapabilitiesFromCache:
Included the missing attributes in callback response. Also removed some unnecessary ones from both service response and callback response.

2024-03-11 16:57 UTC, merged