Creation of service list
openBackhaul/MicroWavePerformanceProxy pull request #5
Opened 2024-02-12 08:49 UTC by anacabbar

Fixes #1 

* Six client services from the MWDI listed (for their purpose see related Íssue)
* Gaps have been left in the sequence-numbers of their uuids. It has been chosen to chose the sequence numbers equal to the corresponding MWDI offered services

2024-02-19 09:55 UTC, kmohr-soprasteria commented on spec/MicroWavePerformanceProxy+services.yaml
> +      release-number: 1.1.0
Release-Version von release-number und der uuid sollten übereinstimmen.

2024-02-19 09:56 UTC, kmohr-soprasteria requested changes
hab eine Kleinigkeit gefunden, Rest war ok :)

2024-02-19 10:10 UTC, kmohr-soprasteria requested changes

2024-02-19 10:10 UTC, kmohr-soprasteria commented on spec/MicroWavePerformanceProxy+services.yaml
> +          - operation-name: /core-model-1-4:network-control-domain=cache/control-construct={mountName}
Vorschlag:
beim A2LT haben wir bei den operation-names auch mitangegeben, welche fields-Filter benutzt werden (als Kommentar); das fand ich sehr hilfreich zum besseren Nachvollziehen, was genau für Daten da abgerufen werden sollen.
(die sollen ja eigentlich hier nicht angegeben werden, aber falls du die auch hilfreich fändest, kann man die auch nachträglich immer noch löschen)

2024-02-19 12:28 UTC, anacabbar commented on spec/MicroWavePerformanceProxy+services.yaml
> +      release-number: 1.1.0
Release-version in release-number updated; it matches now the version written on the uuids

2024-02-20 09:41 UTC, kmohr-soprasteria approved these changes

2024-02-20 10:10 UTC, merged