Creation diagrams
openBackhaul/MicroWavePerformanceProxy pull request #6
Opened 2024-02-12 17:58 UTC by anacabbar

Fixes #2

2024-02-19 11:48 UTC, kmohr-soprasteria requested changes
Insgesamt fehlt mir auch ein Übersichtsdiagramm, wo zu sehen ist, was man dann ganz am Ende zurückliefert.

Am Besten ein Diagramm, wo die einzelnen Forwardings (als Blackboxes) vorkommen (also nur Input und dann der Output vom letzten Schritt) und dann ganz am Ende ein Pfeil zurück zu APT wo steht, was genau zurückgegeben wird.

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +
wieder wie in anderen Diagrammen mountName in der URL statt mount-name
Hinpfeil mit mountName angeben

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +
das verstehe ich nicht,
es ist nicht ersichtlich, wo die Werte auf der rechten Seite herkommen (also LtpUnderTest, ClientStructure usw.)
muss das vor dem Request zugewiesen werden?

Wenn ja dann das angeben und dann darunter ein

FOR each "relevant (mountName, uuid)" pair  <-- mir ist nicht klar, was das für eine uuid ist, die muss näher spezifiert werden, s. auch Kommentar unten)
  <u>GetAugmentPacInfo</u>

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +MWPP -> LtpDesignation: (apiKeyAuth)
da müssen auch die parameter aus der URL angeben werden: mountName und die uuid (mountName ist klar, der ist eindeutig, aber die uuid muss auch näher erklärt werden, ist das die ClientStructureUuid, die ClientContainerUuid oder was ganz anderes?

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +From the following request,
erst das Request durchführen, danach note mit den Zuweisungen machen

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/004_ReadingAirInterfaceCapabilitiesFromCache.plantuml
> +
ich würde hier das RequestForProvidingHistoricalPmDataCausesIdentifyingAirAndEthernetInterfaces als eigenen participant angeben, wie das RequestForProvidingHistoricalPmDataCausesReadingLtpStructure im vorangegangenen Diagramm
Hinpfeil: wieder der mountName
Rückpfeil: list-of-(uuid, localId, linkEndpointName, interfaceName)

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/004_ReadingAirInterfaceCapabilitiesFromCache.plantuml
> +MWPP -> AirInterfaceCapa: {with uuids und localIds of AirInterfaces from RequestForProvidingHistoricalPmDataCausesIdentifyingAirandEthernetInterfaces} (apiKeyAuth)
dann würde ich darüber wieder eine note Box machen
FOR EACH airInterface (uuid, localId)-pair from RequestForProviding...
  <u>GetAirIfCapabilities</u>

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/003_ReadingAirInterfaceConfigurationFromCache.plantuml
> +
ich würde hier das RequestForProvidingHistoricalPmDataCausesIdentifyingAirAndEthernetInterfaces als eigenen participant angeben, wie das RequestForProvidingHistoricalPmDataCausesReadingLtpStructure im vorangegangenen Diagramm
Hinpfeil: wieder der mountName
Rückpfeil: list-of-(uuid, localId, linkEndpointName, interfaceName)

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/003_ReadingAirInterfaceConfigurationFromCache.plantuml
> +MWPP -> AirInterfaceConfig: {with uuids and localIds of the AirInterfaces from RequestForProvidingHistoricalPmDataCausesIdentifyingAirandEthernetInterfaces} (apiKeyAuth)
dann würde ich darüber wieder eine note Box machen
FOR EACH airInterface (uuid, localId)-pair from RequestForProviding...
GetAirIfConfig

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/005_ReadingHistoricalAirInterfacePerformanceFromCache.plantuml
> +
wie bei getConfig/getCapabilities anpassen

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/005_ReadingHistoricalAirInterfacePerformanceFromCache.plantuml
> +note over MWPP
das Problem ist, dass wir nicht direkt auf die richtigen Timestamps filtern können, d.h. wir müssen erst alles abfragen und danach dann den Filter anwenden.
D.h. die Box mit dem Filtern kommt dann nach der Rückantwort vom MWDI,

also die Box so anpassen dass da steht, dass man nur die relevanten Einträge behält und die andren verwirft

2024-02-19 11:48 UTC, kmohr-soprasteria commented on spec/diagrams/006_RetrievingHistoricalEthernetContainerPerformanceFromCache.plantuml
> +
analog zum AirIf-PM-Diagramm anpassen

2024-02-19 11:55 UTC, kmohr-soprasteria commented
Nachtrag: einen Substep-Namen musst du eigentlich nur dann einfügen, wenn du in einem Diagramm mehrere Requests hast, die du ausführst. Bei Diagramm 001 rufst du zwar vorher die LTP Infos ab, aber das ist ja unter einem eigenen Callback, d.h. da kannst du dann in den Descriptions einfach direkt den Callback-Namen aus Diagram 000 angeben.

Das kannst du in meinen Kommentaren also ignorieren.

2024-02-19 12:55 UTC, anacabbar commented on spec/diagrams/000_ReadingLtpStructure.plantuml
> +participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}?fields=logical-termination-point(uuid;server-ltp;client-ltp;layer-protocol(local-id;layer-protocol-name)
Bindestriche in Pfad-Parameter entfernt

2024-02-19 12:55 UTC, anacabbar commented on spec/diagrams/006_RetrievingHistoricalEthernetContainerPerformanceFromCache.plantuml
> +
Bindestriche in allen Pfad-Parametern entfernt

2024-02-19 13:14 UTC, anacabbar commented on spec/diagrams/001_IdentifyingAirAndEthernetInterfaces.plantuml
> +@startuml 001_IdentifyingAirandEthernetInterfaces
Korrigiert, mit großem And geschreiben

2024-02-20 08:41 UTC, anacabbar commented on spec/diagrams/001_IdentifyingAirAndEthernetInterfaces.plantuml
> +
Der Hinpfeil wurde hier mit Absicht nicht gezeichnet. Nach meinem Verständnis enthalten Callbacks bereits die vorhergehenden Verläufe und definierenden Requests mit entsprechenden Eingangsparametern, und es sollte kein Pfeil mit Attributen zum Callback gezeichnet werden.
Siehe z.B. ALAP Diagramme 101_DeterminingAirInterfaceUnderTest, 152_radioComponentIdentifiers, 130_DeterminingLanPortRole.

2024-02-20 08:56 UTC, anacabbar commented on spec/diagrams/001_IdentifyingAirAndEthernetInterfaces.plantuml
> +For all uuids with layerProtocolName == AIR_LAYER
Da in diesem Callback nur ein einzelner Request vorhanden ist, lasse ich es so. Ich werde aber das neue Layout-Modell künftig berücksichtigen  für Callbacks , die mehrere Requests enthalten.

2024-02-20 09:18 UTC, anacabbar commented on spec/diagrams/001_IdentifyingAirAndEthernetInterfaces.plantuml
> +For all uuids with layerProtocolName == AIR_LAYER
"For all" zu "FOR EACH" geändert wie vorgeschlagen

2024-02-20 13:19 UTC, anacabbar commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +From the following request,
Die Notiz gibt die Anweisung, welches Attribut abgefragt werden soll, abhängig vom LayerProtocol. Man könnte dies als zwei alternative Requests interpretieren, die je nach LayerProtocol zu senden sind. 
Der letzte Request liefert selbst keine Informationen über das LayerProtocol. Meiner Meinung nach ist es daher notwendig, die Notiz vor dem Request zu haben.

2024-02-20 13:24 UTC, anacabbar commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +
Beschreibung des Vorgehens geändert, um sie eindeutiger zu machen

2024-02-20 16:36 UTC, anacabbar commented on spec/diagrams/005_ReadingHistoricalAirInterfacePerformanceFromCache.plantuml
> +note over MWPP
Notiz nach dem Request verschoben. Text angepasst, um zu spezifizieren, welche Einträge herauszufiltern sind.

2024-02-21 11:56 UTC, anacabbar commented on spec/diagrams/000_ReadingLtpStructure.plantuml
> +ReadingLtpStructure --> MWPP: {Uuid, LocalId, ServerLtp, ClientLtp, LayerProtocolName}
Eckige Klammern addiert, um Liste zu kennzeichnen

2024-02-21 11:58 UTC, anacabbar commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +From the following request,
Notiz mit Zuweisungen nach dem Request verschoben.

2024-02-21 12:02 UTC, anacabbar commented on spec/diagrams/003_ReadingAirInterfaceConfigurationFromCache.plantuml
> +MWPP -> AirInterfaceConfig: {with uuids and localIds of the AirInterfaces from RequestForProvidingHistoricalPmDataCausesIdentifyingAirandEthernetInterfaces} (apiKeyAuth)
Ich habe stattdessen ein Loop addiert

2024-02-21 12:04 UTC, anacabbar commented on spec/diagrams/004_ReadingAirInterfaceCapabilitiesFromCache.plantuml
> +
Participant addiert (ReadingLtpStructure ist der richtige)
Hinpfeile für Callbacks weggelassen
Eckige Klammern auf dem Rückpfeil, um Liste zu bezeichnen

2024-02-21 12:05 UTC, anacabbar commented on spec/diagrams/004_ReadingAirInterfaceCapabilitiesFromCache.plantuml
> +MWPP -> AirInterfaceCapa: {with uuids und localIds of AirInterfaces from RequestForProvidingHistoricalPmDataCausesIdentifyingAirandEthernetInterfaces} (apiKeyAuth)
Loop stattdessen addiert

2024-02-21 12:05 UTC, anacabbar commented on spec/diagrams/005_ReadingHistoricalAirInterfacePerformanceFromCache.plantuml
> +
Gemacht

2024-02-21 12:08 UTC, anacabbar commented on spec/diagrams/006_RetrievingHistoricalEthernetContainerPerformanceFromCache.plantuml
> +
Gemacht

2024-02-21 15:35 UTC, kmohr-soprasteria requested changes

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/004_ReadingAirInterfaceCapabilitiesFromCache.plantuml
> +
analog zu den Kommentaren von Diagramm 003 anpassen

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/005_ReadingHistoricalAirInterfacePerformanceFromCache.plantuml
> +@startuml 005_ReadingHistoricalAirInterfacePerformanceFromCache
Anpassungen analog zu 003/004

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/006_ReadingHistoricalEthernetContainerPerformanceFromCache copy.plantuml
> +@startuml 006_ReadingHistoricalEthernetContainerPerformanceFromCache
Filename falsch >> copy <<

ansonsten Anpassungen analog zu 003-005

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/999_GlobalMwPerformanceProxy.plantuml
> +@startuml 999_GlobalMwPerformanceProxy
weil die callback-Namen so lang sind, ist das Bild nicht gut leserlich.
Vorschlag (eigentlich ist das nicht so schön, aber in dem Fall würd ich das trotzdem machen):
Zeilenumbrüche einfügen.

Das geht mit "\n" im participant. Die Kursiv-Tags gelten aber immer nur bis zum Zeilenumbruch, d.h. man muss die davor und danach machen.

Also z.B. so:
- statt `participant "<i>RequestForProvidingHistoricalPmDataCausesReadingNameOfAirAndEthernetInterfaces</i>" as Names`
- `participant "<i>RequestForProvidingHistoricalPmDataCauses</i>\n<i>ReadingNameOfAirAndEthernetInterfaces</i>" as Names`

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/999_GlobalMwPerformanceProxy.plantuml
> +end
Es fehlt ein Pfeil mit den Attributen, die an LinkVis zurückgegeben werden

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/999_GlobalMwPerformanceProxy.plantuml
> +LinkVis -> MWPP: [{MountName, timeStamp}<sub>i</sub> (apiKeyAuth)]
ich würde das so machen:
über jedes Request eine notes-Box, wo kurz gesagt wird was man da macht und welcher Schritt das ist (also die Nummer)
also z.B: 
1. read AirIf & EthIf names
2. identify LAGs
3. read AirIf config
4. read AirIf capability
5. read AirIf historical PM
6. read EthIf historical PM


und bei allen Requests auch den Hinpfeil einfügen, mit der Info was an die jeweils übergeben wird; und weil wir ja z.B. die Daten nur für bestimmte uuid/localId Kombinationen ausführen kann in die Textboxen mit den Schritten ruhig wo es sinnvoll ist ein kleiner Satz, dass die gefiltert werden (also z.B. wo layerProtocolName ==AIR_LAYER oder ETH_CONTAINER_LAYER zB). (Also nicht die komplette Logik, sondern nur ganz ganz kurz angegeben).

2024-02-21 15:35 UTC, kmohr-soprasteria commented on spec/diagrams/999_GlobalMwPerformanceProxy.plantuml
> +LinkVis -> MWPP: [{MountName, timeStamp}<sub>i</sub> (apiKeyAuth)]
ich würde auch die Logik noch ein bisschen ändern.
Das timestamp ist ja nur für das Filtern der Historical PM Daten nötig.

D.h. für die Schritte 1-4 brauchen wir das gar nicht; das würde ich nur 1x pro Mountname ausführen, falls da ein Mountname auch mit mehreren Timestamps von LinkVis gesendet werden kann.

Und erst für Schritt 5-6 würde ich das Timestamp mit reinbringen.

D.h. der Loop würde so aussehen:
- äußere Schleife for each mountName: schritte 1-4 
- innere Schleife: for each timestamp (das dann genau zu dem mountName gehört)

Wenn es aber sowieso so ist, dass für jeden Mountname nur 1 timestamp von LinkVis gesendet wird, kann man das auch so lassen, dann würde ich das aber in einer Info-Box kurz dazuschreiben.

2024-02-21 16:10 UTC, anacabbar commented on spec/diagrams/999_GlobalMwPerformanceProxy.plantuml
> +LinkVis -> MWPP: [{MountName, timeStamp}<sub>i</sub> (apiKeyAuth)]
Pro MountName wird es immer nur ein Timestamp von Linkvis gesendet

2024-02-21 16:12 UTC, anacabbar commented on spec/diagrams/006_ReadingHistoricalEthernetContainerPerformanceFromCache copy.plantuml
> +@startuml 006_ReadingHistoricalEthernetContainerPerformanceFromCache
>>copy<< aus dem Filename entfernt

2024-02-21 16:25 UTC, anacabbar commented on spec/diagrams/002_IdentifyingPhysicalLinkAggregations.plantuml
> +	From the request above,
"From request above" entfernt

2024-02-21 16:51 UTC, anacabbar commented on spec/diagrams/999_GlobalMwPerformanceProxy.plantuml
> +@startuml 999_GlobalMwPerformanceProxy
Bzgl. der Umbennenung dieses Diagramms in 000,
Ich hatte mir das auch überlegt, aber es ist evtl. besser, wenn der Leser dieses Diagramm erst am Ende nach den anderen  sieht.

2024-02-21 17:40 UTC, anacabbar commented on spec/diagrams/001_ReadingNameOfAirAndEthernetInterfaces.plantuml
> +    MWPP -> LtpDesignation:{MountName, uuid=AirInterface/EthernetContainerUuid, localId=AirInterface/EthernetContainerLocalId} (apiKeyAuth)
Redundante Details entfernt

2024-02-21 17:42 UTC, anacabbar commented on spec/diagrams/001_ReadingNameOfAirAndEthernetInterfaces.plantuml
> +    From the request above,
Notiz vor dem Request verschoben, da die Information über LayerProtokolName vor dem Request bekannt ist (und nicht dannach)

2024-02-21 17:46 UTC, merged